## Paper Global Configuration
## https://docs.papermc.io/paper/reference/global-configuration

_version: 28

async-chunks:
  threads: -1

chunk-loading-basic:
  autoconfig-send-distance: true
  player-max-chunk-load-rate: -1.0
  player-max-send-chunk-rate: -1.0
  target-player-chunk-send-rate: 100.0

chunk-loading-advanced:
  auto-config-send-distance: true
  player-max-concurrent-loads: 20.0
  player-max-send-chunk-send-rate: -1.0

console:
  enable-brigadier-completions: true
  enable-brigadier-highlights: true
  has-all-permissions: false

item-validation:
  display-name-length: 8192
  lore-line-length: 8192
  resolve-selectors-in-books: false

logging:
  deobfuscate-stacktraces: true
  log-player-ip-addresses: true

messages:
  no-permission: '&cI''m sorry, but you do not have permission to perform this command.'
  kick:
    authentication-servers-down: '&cI''m sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe this is in error.'
    connection-throttle: Connection throttled! Please wait before reconnecting.
    flying-player: Flying is not enabled on this server
    flying-vehicle: Flying is not enabled on this server

misc:
  chat-threads:
    chat-executor-core-size: -1
    chat-executor-max-size: -1
  fix-entity-position-desync: true
  lag-compensate-block-breaking: true
  load-permissions-yml-before-plugins: true
  max-joins-per-tick: 3
  region-file-cache-size: 256
  strict-advancement-dimension-check: false
  use-alternative-luck-formula: false
  use-dimension-type-for-custom-spawners: false

packet-limiter:
  all-packets:
    action: KICK
    interval: 7.0
    max-packet-rate: 500.0
  kick-message: '&cSent too many packets'
  overrides:
    ServerboundPlaceRecipePacket:
      action: DROP
      interval: 4.0
      max-packet-rate: 5.0

player-auto-save:
  max-per-tick: -1
  rate: -1

proxies:
  bungee-cord:
    online-mode: true
  proxy-protocol: false
  velocity:
    enabled: false
    online-mode: false
    secret: ''

scoreboards:
  save-empty-scoreboard-teams: false
  track-plugin-scoreboards: false

spam-limiter:
  incoming-packet-threshold: 300
  recipe-spam-increment: 1
  recipe-spam-limit: 20
  tab-spam-increment: 1
  tab-spam-limit: 500

timings:
  enabled: true
  hidden-config-entries:
  - database
  - proxies.velocity.secret
  history-interval: 300
  history-length: 3600
  server-name: Unknown Server
  server-name-privacy: false
  url: https://timings.aikar.co/

unsupported-settings:
  allow-grindstone-overstacking: false
  allow-headless-pistons: false
  allow-permanent-block-break-exploits: false
  allow-piston-duplication: false
  perform-username-validation: true
  allow-tripwire-disarming-exploits: false
  allow-unsafe-end-portal-teleportation: false

watchdog:
  early-warning-delay: 10000
  early-warning-every: 5000
